# Generated by Django 4.1.7 on 2023-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('shoe_name', models.CharField(max_length=50, verbose_name='Name')),
                ('shoe_image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('website', models.URLField()),
                ('description', models.TextField(default='Shoe')),
            ],
        ),
    ]
